### ISSUE TITLE
Create a roadmap for development

### ISSUE THREAD

**Issue by nicholasjhenry** [montrealrb/Montreal.rb#52]
Below is a proposed roadmap with milestones. Perhaps something we can review together over a hangout before the workshop.

### Introduction

- milestones with the same number can be implemented at the same time, e.g. milestones 1a and 1b can start at the same time
- milestones proceeding a number are dependent on the preceding milestones, e.g. all milestones 2 are dependent on 1, therefore milestones 1 must be completed first (not quite true, but simplifies the roadmap)

### Prerequisites for Workshop

- [x] admin tool (i.e. Thoughtbot's Administrative)
- [x] layout with links based on Wireframe
- [x] home page with placeholders
- [ ] one item from the 1.x milestones to be implemented

### Milestone 1a - Theme: Basic Content Management

- [ ] manage and display news items 
- [ ] manage and display events
- [ ] manage and display pages
- [ ] implement authentication

### Milestone 1b - Theme: Extended Content Management

- [ ] manage and display members
- [ ] manage and display organizations

### Milestone 2a - Theme: Home Page Aggregation

- [ ] aggregate news, events on home page
- [ ] display recent events on home page (sidebar)

### Milestone 2b - Theme: Event Management with Talks

- [ ] manage and display talks assigned to events
- [ ] assign members to talks
- [ ] display talks for a member

### Milestone 2c - Theme: Event Management with Locations

- [ ] manage and display locations assigned to events
- [ ] display a location for an event

### Milestone 2d - Theme: Event Management with Sponsors

- [ ] assign an organization as a sponsor for an event
- [ ] display sponsors for an event

### Milestone 2e - Theme: Jobs Management

- [ ] manage and display jobs
- [ ] assign an organization to a job posting

### Future milestones

- internationalization
- member sign-in with profile and RSVP events
- associating members and organizations

**Comment by benichu** [comment]
Looks good. Only concern is: Workshop is __Tuesday__
Will we have time to finish the prerequisites in time?
If we need to strip that down:
* `implement authentication` -> __could be done by a team during the workshop__ 
* `one item from the 1.x milestones to be implemented` -> __let's go commando, and introduce the attendees to thoughtbot/administrate at the beginning of the workshop, and let each team use it for their module__ 

Which would leave us with 3 items to do before tuesday:
- admin tool (i.e. Thoughtbot's Administrative)
- layout with links based on Wireframe
- home page with placeholders

Who can work on what? I can try to fit in a hangout and a couple of hours on sunday and monday...

**Comment by benichu** [comment]
As a side note, If a decision has been made regarding #4, we need some cleanup and/or preparations tasks (ex: cleanup DB schema if we don't use globalize yet...)

**Comment by sophiedeziel** [comment]
I am tempted to reply with a long long long text. But I'll give you a TL;DR right now for free, without the long text: I agree with everything @benichu said. 

@nicholasjhenry's roadmap is great!

**Comment by mathieugagne** [comment]
Now that it seems a decision has been made for #4, where does it fit?

Suggestion:

### Milestone 3 - Theme: Internationalization

- Import translations for all past items
- Translate layout, error messages and other application-related items

**Comment by sophiedeziel** [comment]
Yep, milestone 3 :) Do we have to add anything to our administration tools to manage translations? If so, it should be a step in the milestone. Also, once everything is localized, we should add internationalization as a requirement for future contributions.

**Comment by nicholasjhenry** [comment]
> Milestone 3 - Theme: Internationalization

I've added I18n as a future milestone.

> Do we have to add anything to our administration tools to manage translations?

No, it just works :-)

**Comment by sophiedeziel** [comment]
Oh! And you checklisted all the things! That's awesome!

**Comment by nicholasjhenry** [comment]
This has been moved to the wiki.
